### ISSUE TITLE
Does not work on AngularJS 1.4.x

### ISSUE THREAD

**Issue by rfornal-ssi** [anandthakker/angular-multirange-slider#4]
Several errors occur.

TypeError: Cannot read property 'push' of undefined at compile.pre (76)
TypeError: Cannot read property 'push' of undefined at link (126)
TypeError: Cannot read property 'push' of undefined at compile.pre (76)
TypeError: Cannot read property 'push' of undefined at link (126)
TypeError: Cannot read property 'push' of undefined at compile.pre (76)
TypeError: Cannot read property 'push' of undefined at link (126)
TypeError: slider.updateRangeWidths is not a function at Object.fn (74)

It does work, as long as I stay in the 1.3.x branch of AngularJS ... http://plnkr.co/edit/Bn1Y1YQnWIcgblFqAdPd?p=preview

**Comment by dkiyatkin** [comment]
This pull fix that, https://github.com/anandthakker/angular-multirange-slider/pull/5
Or you can use my branch.

**Comment by rfornal-ssi** [comment]
Thanks for that ... switching to your repo!

**Comment by anandthakker** [comment]
Fixed in #5, thanks @dkiyatkin

**Comment by OoDeLally** [comment]
Same problem with 1.6.1.
To reproduce it, take the `example.html` file and replace
```
  <script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js'></script>
```
by
```
  <script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js'></script>
```
